############################################################################
# 1. Namespace
############################################################################
apiVersion: v1
kind: Namespace
metadata:
  name: airflow
---
############################################################################
# 2. PostgreSQL Deployment (Airflow Metadata DB)
############################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-postgres
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-postgres
  template:
    metadata:
      labels:
        app: airflow-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "airflow"
        - name: POSTGRES_PASSWORD
          value: "airflow"
        - name: POSTGRES_DB
          value: "airflow"
        resources:
          requests:
            cpu: "250m"
            memory: "1Gi"
          limits:
            cpu: "500m"
            memory: "2Gi"
---
############################################################################
# 3. PostgreSQL Service
############################################################################
apiVersion: v1
kind: Service
metadata:
  name: airflow-postgres
  namespace: airflow
spec:
  selector:
    app: airflow-postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
---
############################################################################
# 4. Shared Volume Definition (for DAGs and include)
############################################################################
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-shared-pvc
  namespace: airflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
############################################################################
# 5. Airflow Scheduler Deployment
############################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      component: scheduler
  template:
    metadata:
      labels:
        component: scheduler
    spec:
      initContainers:
      - name: migrate-db
        image: apache/airflow:3.0.0
        command: ["airflow", "db", "migrate"]
        env:
        - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
          value: "postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow"
        - name: AIRFLOW__CORE__EXECUTOR
          value: "LocalExecutor"
      containers:
      - name: scheduler
        image: apache/airflow:3.0.0
        command: ["sh", "-c", "pip install -r /shared/dags/requirements.txt && airflow scheduler"]
        env:
        - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
          value: "postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow"
        - name: AIRFLOW__CORE__EXECUTOR
          value: "LocalExecutor"
        - name: AIRFLOW__CORE__DAGS_FOLDER
          value: "/shared/dags"
        volumeMounts:
        - name: shared-volume
          mountPath: /shared
        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
      - name: git-sync
        image: k8s.gcr.io/git-sync/git-sync:v3.6.8
        env:
        - name: GIT_SYNC_REPO
          value: "https://github.com/bkpatel95/DAGs.git"
        - name: GIT_SYNC_BRANCH
          value: "main"
        - name: GIT_SYNC_ROOT
          value: "/shared"
        - name: GIT_SYNC_DEST
          value: "dags"
        - name: GIT_SYNC_ONE_TIME
          value: "false"
        - name: GIT_SYNC_WAIT
          value: "30"
        volumeMounts:
        - name: shared-volume
          mountPath: /shared
      volumes:
      - name: shared-volume
        persistentVolumeClaim:
          claimName: airflow-shared-pvc
---
############################################################################
# 6. Airflow API Server Deployment
############################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-api-server
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api-server
  template:
    metadata:
      labels:
        component: api-server
    spec:
      containers:
      - name: api-server
        image: apache/airflow:3.0.0
        command: ["sh", "-c", "pip install -r /shared/dags/requirements.txt && airflow api-server"]
        env:
        - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
          value: "postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow"
        - name: AIRFLOW__CORE__EXECUTOR
          value: "LocalExecutor"
        - name: AIRFLOW__CORE__DAGS_FOLDER
          value: "/shared/dags"
        - name: AIRFLOW__MANAGED__DEFAULT_USERNAME
          value: "admin"
        - name: AIRFLOW__MANAGED__DEFAULT_PASSWORD
          value: "admin"
        - name: AIRFLOW__MANAGED__DEFAULT_EMAIL
          value: "bhavip45@gmail.com"
        volumeMounts:
        - name: shared-volume
          mountPath: /shared
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "2Gi"
      - name: git-sync
        image: k8s.gcr.io/git-sync/git-sync:v3.6.8
        env:
        - name: GIT_SYNC_REPO
          value: "https://github.com/bkpatel95/DAGs.git"
        - name: GIT_SYNC_BRANCH
          value: "main"
        - name: GIT_SYNC_ROOT
          value: "/shared"
        - name: GIT_SYNC_DEST
          value: "dags"
        - name: GIT_SYNC_ONE_TIME
          value: "false"
        - name: GIT_SYNC_WAIT
          value: "30"
        volumeMounts:
        - name: shared-volume
          mountPath: /shared
      volumes:
      - name: shared-volume
        persistentVolumeClaim:
          claimName: airflow-shared-pvc
---
############################################################################
# 7. Airflow API Server Service (NodePort)
############################################################################
apiVersion: v1
kind: Service
metadata:
  name: airflow-api-server
  namespace: airflow
spec:
  type: NodePort
  selector:
    component: api-server
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080
---
############################################################################
# 8. Airflow Triggerer Deployment
############################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-triggerer
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      component: triggerer
  template:
    metadata:
      labels:
        component: triggerer
    spec:
      containers:
      - name: triggerer
        image: apache/airflow:3.0.0
        command: ["sh", "-c", "pip install -r /shared/dags/requirements.txt && airflow triggerer"]
        env:
        - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
          value: "postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow"
        - name: AIRFLOW__CORE__EXECUTOR
          value: "LocalExecutor"
        - name: AIRFLOW__CORE__DAGS_FOLDER
          value: "/shared/dags"
        volumeMounts:
        - name: shared-volume
          mountPath: /shared
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "2Gi"
      volumes:
      - name: shared-volume
        persistentVolumeClaim:
          claimName: airflow-shared-pvc
