---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyterserver
  labels:
    app: jupyterserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyterserver
  template:
    metadata:
      labels:
        app: jupyterserver
    spec:
      containers:
      - name: jupyterserver
        image: jupyter/base-notebook:latest
        ports:
        - containerPort: 8888
        env:
        - name: JUPYTER_ENABLE_LAB
          value: "yes"
        args:
        - "start.sh"
        - "jupyter"
        - "lab"
        - "--LabApp.token=''"
        - "--LabApp.password=''"
        volumeMounts:
        - name: workspace
          mountPath: /home/jovyan
      volumes:
      - name: workspace
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: jupyterserver
spec:
  type: NodePort
  selector:
    app: jupyterserver
  ports:
  - port: 8888
    targetPort: 8888
    nodePort: 30888