---
apiVersion: v1
kind: Namespace
metadata:
  name: postgreSQL
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: postgreSQL
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
  storageClassName: faster-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-stock
  namespace: postgreSQL
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-stock
  template:
    metadata:
      labels:
        app: postgres-stock
    spec:
      containers:
      - name: postgres
        image: postgres:13
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_PASSWORD
          value: "admin"
        - name: POSTGRES_DB
          value: "stockdb"
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-stock
  namespace: postgreSQL
spec:
  selector:
    app: postgres-stock
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  type: ClusterIP
