---
apiVersion: v1
kind: Namespace
metadata:
  name: superset

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: superset-pvc
  namespace: superset
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: faster-storage

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset
  namespace: superset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superset
  template:
    metadata:
      labels:
        app: superset
    spec:
      containers:
      - name: superset
        image: apache/superset:latest  # Use the latest Superset image
        command:
        - "/bin/sh"
        - "-c"
        - |
          superset init && 
          sed -i "s/SECRET_KEY =.*/SECRET_KEY = \"$(openssl rand -hex 32)\"/" /app/superset_home/pythonpath/superset/config.py &&
          superset run -h 0.0.0.0 -p 8088 --with-threads --reload --debugger
        ports:
        - containerPort: 8088
        env:
        - name: FLASK_APP
          value: superset
        - name: SUPERSET__SQLALCHEMY_DATABASE_URI
          value: postgresql://admin:admin@postgres-stock.postgresql.svc.cluster.local:5432/superset  # Update with your PostgreSQL details
        # Add other environment variables for Superset configuration if needed
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 2
            memory: 4Gi
        volumeMounts:
        - name: superset-data
          mountPath: /app/superset_home
      volumes:
      - name: superset-data
        persistentVolumeClaim:
          claimName: superset-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: superset
  namespace: superset
spec:
  type: NodePort
  selector:
    app: superset
  ports:
  - protocol: TCP
    port: 8088
    targetPort: 8088
    nodePort: 30082  # Choose a NodePort that doesn't conflict with other services
