---
apiVersion: v1
kind: Namespace
metadata:
  name: superset

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: superset-config
  namespace: superset
data:
  superset_config.py: |
    # Superset configuration file
    # You can add additional configurations here.
    SECRET_KEY = "default"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: superset-pvc
  namespace: superset
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: faster-storage

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset
  namespace: superset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superset
  template:
    metadata:
      labels:
        app: superset
    spec:
      containers:
      - name: superset
        image: apache/superset:latest  # Use the latest Superset image
        command:
        - "/bin/sh"
        - "-c"
        - |
          SECRET=$(python3 -c "import secrets; print(secrets.token_hex(42))") && \
          sed -i "s/SECRET_KEY =.*/SECRET_KEY = \"$SECRET\"/" /app/superset_config.py && \
          superset init && \
          superset run -h 0.0.0.0 -p 8088 --with-threads --reload --debugger
        ports:
        - containerPort: 8088
        env:
        - name: FLASK_APP
          value: superset
        - name: SUPERSET__SQLALCHEMY_DATABASE_URI
          value: postgresql://admin:admin@postgres-stock.postgresql.svc.cluster.local:5432/superset
        - name: SUPERSET_CONFIG_PATH
          value: /app/superset_config.py
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 2
            memory: 4Gi
        volumeMounts:
        # Mount the persistent volume for data
        - name: superset-data
          mountPath: /app
        # Mount the config file from the ConfigMap at the correct location using subPath
        - name: superset-config
          mountPath: /app/superset_config.py
          subPath: superset_config.py
      volumes:
      - name: superset-data
        persistentVolumeClaim:
          claimName: superset-pvc
      - name: superset-config
        configMap:
          name: superset-config

---
apiVersion: v1
kind: Service
metadata:
  name: superset
  namespace: superset
spec:
  type: NodePort
  selector:
    app: superset
  ports:
  - protocol: TCP
    port: 8088
    targetPort: 8088
    nodePort: 30082
