apiVersion: v1
kind: Namespace
metadata:
  name: superset
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset
  namespace: superset
  labels:
    app: superset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superset
  template:
    metadata:
      labels:
        app: superset
    spec:
      containers:
      - name: superset
        image: apache/superset:latest
        ports:
        - containerPort: 32148
        env:
          - name: SUPERSET_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: superset-secrets
                key: SUPERSET_SECRET_KEY
          - name: DATABASE_URL
            value: "postgresql://admin:admin@postgres-stock.postgresql.svc.cluster.local:5432/stockdb"
          # Environment variables for automatic admin creation:
          - name: ADMIN_USERNAME
            value: "admin"
          - name: ADMIN_FIRSTNAME
            value: "Admin"
          - name: ADMIN_LASTNAME
            value: "User"
          - name: ADMIN_EMAIL
            value: "bhavip45@gmail.com"
          - name: ADMIN_PASSWORD
            value: "admin"
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
        readinessProbe:
          httpGet:
            path: /
            port: 32148
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 32148
          initialDelaySeconds: 60
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: superset-svc   # Renamed to avoid auto-injection of SUPERSET_PORT
  namespace: superset
  labels:
    app: superset
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 32148
  selector:
    app: superset
